"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from environs import Env

env = Env()

# ================================
# 基本設定
# ================================
config_dir = Path(__file__).resolve().parent
backend_dir = config_dir.parent
# ENV_FILE が指定されていればそれを使い、なければ backend/.env.venv を読む
default_env_file = backend_dir / ".env.venv"
env_file = env.str("ENV_FILE", default=str(default_env_file))
env.read_env(env_file)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------
# DJANGO_ENV による環境切り替え
# -------------------------------
DJANGO_ENV = env.str("DJANGO_ENV", default="production").lower()

IS_PRODUCTION = DJANGO_ENV == "production"
IS_DEVELOPMENT = DJANGO_ENV == "development"


# -------------------------------
# セキュリティ設定
# -------------------------------
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # 3rd-party apps
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Local
    "apps.accounts.apps.AccountsConfig",
    "apps.api.apps.ApiConfig",
    "apps.climate_data.apps.ClimateDataConfig",
    "apps.dataset.apps.DatasetConfig",
]

# ================================
# SITE
# ================================
SITE_ID = 1

# ================================
# DRF / 認証
# ================================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# 開発環境のみ Browsable API と SessionAuth を追加
if IS_DEVELOPMENT:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].append(
        "rest_framework.authentication.SessionAuthentication"
    )
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
        "rest_framework.renderers.BrowsableAPIRenderer"
    )

# ================================
# dj-rest-auth / Cookie 設定
# ================================
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",
}

# 本番だけ Secure + SameSite=None
if IS_PRODUCTION:
    REST_AUTH.update(
        {
            "JWT_AUTH_SECURE": True,  # HTTPS 必須
            "JWT_AUTH_SAMESITE": "None",  # クロスオリジン対応
        }
    )

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

# ================================
# drf-spectacular (OpenAPI/Swagger)
# ================================
GENERATE_SCHEMA = env.bool("GENERATE_SCHEMA", default=False)

if GENERATE_SCHEMA:
    INSTALLED_APPS += [
        "drf_spectacular",
    ]

    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"  # type: ignore

    SPECTACULAR_SETTINGS = {
        "TITLE": "Climate Change App (Django REST Framework + React)",
        "DESCRIPTION": "A climate change app for learning about climate change with data visualization.",
        "VERSION": "1.0.0",
    }

# ================================
# CORS
# ================================
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = env.list(
    "CORS_ORIGIN_WHITELIST",
    default=[
        "http://localhost:3000",
    ],
)

# ================================
# Middleware
# ================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# ================================
# Templates / Static
# ================================
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ================================
# DB
# ================================
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {"default": env.dj_db_url("DATABASE_URL", default="sqlite:///db.sqlite3")}

# ================================
# 認証ユーザモデル
# ================================
AUTH_USER_MODEL = "accounts.CustomUser"

# ================================
# パスワードバリデーション
# ================================
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ================================
# Email
# ================================
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# ================================
# その他
# ================================
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "ja"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ================================
# Static files
# ================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ================================
# Media files (uploads)
# ================================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ================================
# Celery (development only)
# ================================
if IS_DEVELOPMENT:
    CELERY_TIMEZONE = TIME_ZONE
    CELERY_ENABLE_UTC = True

    # 開発環境では worker なしで即時実行
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# ================================
# App-specific settings
# ================================

# ================================
# 警告無視設定（古い allauth 設定による UserWarning を無視）
# ================================
import warnings

warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    message="app_settings.*is deprecated.*",
)
