serviceAccount: vizshare-prod-cbr@${PROJECT_ID}.iam.gserviceaccount.com

steps:
  # ----------------------------
  # ① Build Image
  # ----------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
        "-f",
        "backend/docker/Dockerfile.prod",
        "backend",
      ]

  # ----------------------------
  # ② Push Image
  # ----------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
      ]

  # ----------------------------
  # ③ Update migration job image
  # ----------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "jobs",
        "update",
        "${_APP_NAME}-prod-migrate",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
        "--region",
        "asia-northeast1",
      ]

  # ----------------------------
  # ④ Run migrations
  # ----------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "jobs",
        "execute",
        "${_APP_NAME}-prod-migrate",
        "--region",
        "asia-northeast1",
        "--wait",
      ]

  # ----------------------------
  # ⑤ Deploy Cloud Run Service
  # ----------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "${_APP_NAME}",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "vizshare-django-prod-sa@${PROJECT_ID}.iam.gserviceaccount.com",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s
