# Cloud Build を実行する Service Account
serviceAccount: cloud-build-runner-tf@${PROJECT_ID}.iam.gserviceaccount.com

steps:
  # ステップ 1: Docker イメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
        "-f",
        "backend/docker/Dockerfile.prod",
        "backend",
      ]

  # ステップ 2: Docker イメージを Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
      ]

  # ステップ 3: Cloud Run にデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: [
        "gcloud",
        "run",
        "deploy",
        "${_APP_NAME}", # サービス名も _APP_NAME で管理
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_APP_NAME}/${_APP_NAME}-image:$COMMIT_SHA",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "django-app-sa@$PROJECT_ID.iam.gserviceaccount.com",
      ]

# オプション: ロギング設定
options:
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定（600秒 = 10分）
timeout: 600s
