/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/climate/co2-data/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description フロント用 API
         *     /climate/co2-data/
         */
        get: operations["climate_co2_data_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/climate/temperature/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 気温データ取得
         * @description 地域・年ごとの気温データを返します。upper, lower, global_average を含みます。
         */
        get: operations["climate_temperature_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dataset/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Dataset のアップロード専用 API
         *     Next.js からファイルをアップロード可能
         */
        post: operations["dataset_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Check the credentials and return the REST Token
         *     if the credentials are valid and authenticated.
         *     Calls Django Auth login method to register User ID
         *     in Django session framework
         *
         *     Accept the following POST parameters: username, password
         *     Return the REST Framework Token Object's key.
         */
        post: operations["dj_rest_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django logout method and delete the Token object
         *     assigned to the current User object.
         *
         *     Accepts/Returns nothing.
         */
        post: operations["dj_rest_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth SetPasswordForm save method.
         *
         *     Accepts the following POST parameters: new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["dj_rest_auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth PasswordResetForm save method.
         *
         *     Accepts the following POST parameters: email
         *     Returns the success/fail message.
         */
        post: operations["dj_rest_auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Password reset e-mail link is confirmed, therefore
         *     this resets the user's password.
         *
         *     Accepts the following POST parameters: token, uid,
         *         new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["dj_rest_auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/registration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Registers a new user.
         *
         *     Accepts the following POST parameters: username, email, password1, password2.
         */
        post: operations["dj_rest_auth_registration_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/registration/resend-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Resends another email to an unverified email.
         *
         *     Accepts the following POST parameter: email.
         */
        post: operations["dj_rest_auth_registration_resend_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/registration/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Verifies the email associated with the provided key.
         *
         *     Accepts the following POST parameter: key.
         */
        post: operations["dj_rest_auth_registration_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["dj_rest_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["dj_rest_auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dj-rest-auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        get: operations["dj_rest_auth_user_retrieve"];
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        put: operations["dj_rest_auth_user_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        patch: operations["dj_rest_auth_user_partial_update"];
        trace?: never;
    };
    "/api/v1/health/ping/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ウォームアップ用 ping */
        get: operations["health_ping_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 年ごとの国別CO2排出量を返すSerializer。
         *
         *     co2_data の構造例:
         *     {
         *         "2000": { "JPN": 1000.0, "USA": 5000.0 },
         *         "2001": { "JPN": 1100.0, "USA": 5200.0 }
         *     }
         *     - 外側のキー: 年（year）
         *     - 内側のキー: 地域コード
         *     - 内側の値: CO2排出量（tonnes）
         */
        CO2DataByYear: {
            /** @description 年ごとの国別CO2排出量。例: { '2000': {'JPN': 1000.0, 'USA': 5000.0} } */
            co2_data: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        Dataset: {
            readonly id: number;
            name: string;
            /** Format: uri */
            source_file: string;
            readonly owner: number;
            readonly status: string;
            schema?: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Serializer for JWT authentication. */
        JWT: {
            access: string;
            refresh: string;
            user: components["schemas"]["UserDetails"];
        };
        Login: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        PasswordChange: {
            new_password1: string;
            new_password2: string;
        };
        /** @description Serializer for requesting a password reset e-mail. */
        PasswordReset: {
            /** Format: email */
            email: string;
        };
        /** @description Serializer for confirming a password reset attempt. */
        PasswordResetConfirm: {
            new_password1: string;
            new_password2: string;
            uid: string;
            token: string;
        };
        /** @description User model w/o password */
        PatchedUserDetails: {
            /** ID */
            readonly pk?: number;
            /**
             * ユーザー名
             * @description この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
             */
            username?: string;
            /**
             * メールアドレス
             * Format: email
             */
            readonly email?: string;
            /** 名 */
            first_name?: string;
            /** 姓 */
            last_name?: string;
        };
        Ping: {
            message: string;
        };
        Register: {
            username: string;
            /** Format: email */
            email?: string;
            password1: string;
            password2: string;
        };
        ResendEmailVerification: {
            /** Format: email */
            email?: string;
        };
        RestAuthDetail: {
            readonly detail: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        /** @description User model w/o password */
        UserDetails: {
            /** ID */
            readonly pk: number;
            /**
             * ユーザー名
             * @description この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
             */
            username: string;
            /**
             * メールアドレス
             * Format: email
             */
            readonly email: string;
            /** 名 */
            first_name?: string;
            /** 姓 */
            last_name?: string;
        };
        VerifyEmail: {
            key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    climate_co2_data_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CO2DataByYear"];
                };
            };
        };
    };
    climate_temperature_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            year?: number;
                            /** Format: double */
                            upper?: number | null;
                            /** Format: double */
                            lower?: number | null;
                            /** Format: double */
                            global_average?: number | null;
                        }[];
                    };
                };
            };
        };
    };
    dataset_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dataset"];
                "application/x-www-form-urlencoded": components["schemas"]["Dataset"];
                "multipart/form-data": components["schemas"]["Dataset"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
        };
    };
    dj_rest_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWT"];
                };
            };
        };
    };
    dj_rest_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
                "multipart/form-data": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_registration_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWT"];
                };
            };
        };
    };
    dj_rest_auth_registration_resend_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResendEmailVerification"];
                "application/x-www-form-urlencoded": components["schemas"]["ResendEmailVerification"];
                "multipart/form-data": components["schemas"]["ResendEmailVerification"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_registration_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    dj_rest_auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    dj_rest_auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    dj_rest_auth_user_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["UserDetails"];
                "multipart/form-data": components["schemas"]["UserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    dj_rest_auth_user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDetails"];
                "multipart/form-data": components["schemas"]["PatchedUserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    health_ping_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ping"];
                };
            };
        };
    };
}
