@startuml vizshare_use
skinparam defaultFontName "Noto Sans CJK JP"
left to right direction

actor GeneralUser as generalUser

rectangle "Vizshare App" {
  package "Data Handling" {
    (Upload CSV)
    (Visualize Data)
  }
  
  package "Sharing & Interaction" {
    (Share Data)
    (Browse Public Datasets)
    (View Shared Visualizations)
    (Comment)
  }
}

generalUser --> (Upload CSV)
generalUser --> (Visualize Data)
generalUser --> (Share Data)
generalUser --> (Browse Public Datasets)
generalUser --> (View Shared Visualizations)
generalUser --> (Comment)

@enduml