name: Terraform Plan (Staging)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: "projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "vizshare-staging-terraform-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra/staging
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/staging
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_VAR_region: asia-northeast1
          TF_VAR_project_number: ${{ secrets.PROJECT_NUMBER }}
        run: |
          terraform plan -detailed-exitcode
          PLAN_EXIT_CODE=$?
          if [ $PLAN_EXIT_CODE -eq 2 ]; then
            echo "⚠️ Terraform has changes!"
            # ここで exit 1 にすると CI を fail させる
            # exit 1
          elif [ $PLAN_EXIT_CODE -eq 1 ]; then
            echo "❌ Terraform plan error!"
            exit 1
          else
            echo "✅ No changes in Terraform"
          fi
